const test=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const {createPortalMessagingHandler,messagingToken}=require('../netlify/functions/portal-messaging')._test;
const env={SYNTHETIC_PORTAL_MESSAGING_ENABLED:'true',HEALTH_CORE_API_URL:'https://health.example.test',CREWHQ_CLOUD_TOKEN_SECRET:'synthetic-staff-secret'};
const session={staffId:'frontdesk',name:'Synthetic front desk',role:'staff'};
const command={action:'reply',commandId:crypto.randomUUID(),threadId:'msg-'+'a'.repeat(40),expectedRevision:1,body:'Synthetic reply'};
const event=(body=command)=>({httpMethod:body?'POST':'GET',headers:{},body:body?JSON.stringify(body):undefined});
test('staff proxy uses a 60-second purpose-scoped server token and does not expose credentials',async()=>{let observed;const handle=createPortalMessagingHandler({environment:env,sessionImpl:()=>session,fetchImpl:async(url,options)=>{observed={url,options};return Response.json({ok:true,thread:{},commandId:command.commandId});}});const r=await handle(event());assert.equal(r.statusCode,200);assert.equal(observed.url,'https://health.example.test/v1/portal-messaging/inbox');const claims=JSON.parse(Buffer.from(observed.options.headers.Authorization.slice(7).split('.')[0],'base64url').toString());assert.equal(claims.scope,'portal-messaging');assert.equal(claims.sub,'crew:frontdesk');assert.equal(claims.exp-claims.iat,60);assert.equal('token' in JSON.parse(r.body),false);assert.equal(observed.options.redirect,'error');});
test('staff proxy fails closed for absent session, disabled service, real patient and untrusted upstream URL',async()=>{let count=0;const fetchImpl=async()=>{count++;return Response.json({ok:true});};for(const [sessionImpl,environment,body,status] of [[()=>null,env,command,401],[()=>session,{...env,SYNTHETIC_PORTAL_MESSAGING_ENABLED:'false'},command,503],[()=>session,env,{...command,bhwPatientId:'BHW1234'},403],[()=>session,{...env,HEALTH_CORE_API_URL:'http://example.test'},command,503]]){const handle=createPortalMessagingHandler({environment,sessionImpl,fetchImpl});assert.equal((await handle(event(body))).statusCode,status);}assert.equal(count,0);});
test('staff proxy preserves denied grants and conflicts, and flags uncertain saves',async()=>{for(const status of [403,409,429]){const h=createPortalMessagingHandler({environment:env,sessionImpl:()=>session,fetchImpl:async()=>Response.json({ok:false,error:'Denied'},{status})});assert.equal((await h(event())).statusCode,status);}const h=createPortalMessagingHandler({environment:env,sessionImpl:()=>session,fetchImpl:async()=>{throw Error('timeout');}});assert.equal(JSON.parse((await h(event())).body).saveUnconfirmed,true);});
test('no command receipt cannot be mistaken for a saved staff reply',async()=>{const h=createPortalMessagingHandler({environment:env,sessionImpl:()=>session,fetchImpl:async()=>Response.json({ok:true})});assert.equal((await h(event())).statusCode,502);assert.equal(messagingToken(session,env.CREWHQ_CLOUD_TOKEN_SECRET).split('.').length,2);});
test('staff binary file delivery is private, authenticated and bound to the requested file',async()=>{
 const bytes=Buffer.from('Synthetic patient file');const file={id:'att-'+'a'.repeat(40),name:'synthetic.txt',size:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),contentBase64:bytes.toString('base64')};const input={...event(null),queryStringParameters:{threadId:command.threadId,attachmentId:file.id}};let calls=0;
 const h=createPortalMessagingHandler({environment:env,sessionImpl:()=>session,fetchImpl:async()=>{calls++;return Response.json({ok:true,attachment:file});}});const r=await h(input);assert.equal(r.statusCode,200);assert.equal(r.isBase64Encoded,true);assert.equal(r.headers['Content-Type'],'application/octet-stream');assert.equal(r.headers['Content-Disposition'],'attachment; filename="synthetic.txt"');assert.equal(r.headers['Cache-Control'],'no-store, private');assert.equal(r.body,file.contentBase64);
 const anonymous=createPortalMessagingHandler({environment:env,sessionImpl:()=>null,fetchImpl:async()=>{calls++;}});assert.equal((await anonymous(input)).statusCode,401);assert.equal((await h({...input,queryStringParameters:{attachmentId:file.id}})).statusCode,400);assert.equal(calls,1);
 const corrupt=createPortalMessagingHandler({environment:env,sessionImpl:()=>session,fetchImpl:async()=>Response.json({ok:true,attachment:{...file,sha256:'0'.repeat(64)}})});assert.equal((await corrupt(input)).statusCode,502);
});
test('staff bridge forwards file commands unchanged and preserves unsafe-file rejection',async()=>{
 const file={name:'synthetic.txt',mediaType:'text/plain',contentBase64:Buffer.from('Synthetic').toString('base64')};const input={...command,attachments:[file]};let forwarded;
 const h=createPortalMessagingHandler({environment:env,sessionImpl:()=>session,fetchImpl:async(url,options)=>{forwarded=JSON.parse(options.body);return Response.json({ok:false,error:'Unsafe file.'},{status:422});}});assert.equal((await h(event(input))).statusCode,422);assert.deepEqual(forwarded.attachments,input.attachments);
});
